import random
import time

truths = [
    "What’s the most embarrassing thing you’ve ever done in public?",
    "Who was your first crush?",
    "Have you ever had a crush on a teacher?",
    "What’s the worst lie you’ve ever told?",
    "Have you ever cheated in an exam?",
    "What’s your biggest fear?",
    "What’s a secret you’ve never told anyone?",
    "Have you ever been caught lying?",
    "Who’s the last person you stalked on social media?",
    "What’s the dumbest thing you’ve ever done for love?",
    "What’s the most childish thing you still do?",
    "If you could erase one memory, what would it be?",
    "What’s your guilty pleasure?",
    "Have you ever liked your best friend’s crush?",
    "What’s something you regret saying recently?",
    "If you had to marry one person here, who would it be?",
    "What’s the most awkward date you’ve been on?",
    "What’s your most useless talent?",
    "What’s a habit you can’t quit?",
    "When was the last time you cried?",
    "Have you ever broken someone’s heart?",
    "Have you ever been heartbroken?",
    "What’s the worst thing you’ve ever said to someone?",
    "If you could switch lives with someone for a day, who would it be?",
    "What’s the most expensive thing you’ve ever bought?",
    "Have you ever ghosted someone?",
    "What’s one thing you’d change about yourself?",
    "What’s the biggest mistake you’ve ever made?",
    "Have you ever pretended to like someone?",
    "What’s the weirdest dream you’ve ever had?",
    "What’s your go-to excuse for skipping plans?",
    "What’s your most overused emoji?",
    "If your life were a movie, what would the title be?",
    "Who in this group do you think is most likely to go to jail?",
    "Have you ever been caught doing something you shouldn’t?",
    "What’s the most awkward thing you’ve said to your crush?",
    "Have you ever sent a text to the wrong person?",
    "What’s your biggest insecurity?",
    "What’s the strangest rumor you’ve heard about yourself?",
    "What’s one thing you’ve done that your parents would disapprove of?",
    "Have you ever lied to your best friend?",
    "What’s a secret talent no one knows about?",
    "If you could know one secret about anyone here, whose would it be?",
    "Who here do you think would survive a zombie apocalypse the longest?",
    "What’s the longest you’ve gone without showering?",
    "What’s something you’d never want your parents to find out?",
    "Who’s your celebrity crush?",
    "What’s the meanest thing you’ve ever done?",
    "Have you ever faked being sick to skip school or work?",
    "If you could change your name, what would it be?",
    "What’s the weirdest food combo you actually like?",
    "What’s the most embarrassing photo of you?",
    "What’s one thing you wish you were better at?",
    "What’s your worst habit?",
    "What’s the biggest secret you’ve kept from your parents?",
    "Who do you text the most?",
    "What’s the stupidest reason you’ve cried?",
    "What’s your worst fashion decision ever?",
    "Have you ever been caught talking to yourself?",
    "What’s the weirdest nickname you’ve ever had?",
    "Who was your childhood hero?",
    "Have you ever laughed at the wrong moment?",
    "What’s your favorite excuse for being late?",
    "Have you ever lied to get out of trouble?",
    "What’s the weirdest thing you’ve ever Googled?",
    "What’s something you’ve done that you’d never tell your family?",
    "Have you ever had a crush on someone here?",
    "What’s the worst gift you’ve ever received?",
    "If you could delete one person from your contacts, who would it be?",
    "Have you ever gotten into a fight with your best friend?",
    "What’s your most irrational fear?",
    "What’s a lie you tell yourself often?",
    "What’s one thing you’d do if you knew there’d be no consequences?",
    "Who’s the last person you texted before this game?",
    "What’s one thing you’ve done that you still can’t believe you did?",
    "Have you ever stolen something (even small)?",
    "What’s your most embarrassing school memory?"
]


dares = [
    "Do your best dance move for 20 seconds.",
    "Talk in a fake accent for the next 3 rounds.",
    "Sing the chorus of a song loudly for 15 seconds.",
    "Imitate your favorite celebrity for 30 seconds.",
    "Text your crush 'We need to talk...' with no context.",
    "Act like a cat until your next turn.",
    "Do 10 push-ups right now.",
    "Eat a spoonful of ketchup or sauce.",
    "Speak only in rhymes for the next 2 rounds.",
    "Do your best impression of your teacher.",
    "Post a weird selfie on your social media story with no caption.",
    "Balance something on your head for 30 seconds.",
    "Try to lick your elbow (and don’t stop until everyone’s satisfied).",
    "Let someone write something on your hand with a pen.",
    "Talk like a robot until your next turn.",
    "Do your best evil laugh.",
    "Say the alphabet backward as fast as you can.",
    "Tell a bad joke — if no one laughs, you do another dare.",
    "Pretend to be a waiter/waitress and take everyone’s order.",
    "Sing everything you say for the next minute.",
    "Reveal the last photo you took on your phone.",
    "Let someone go through your YouTube history for 15 seconds.",
    "Do your best impression of a crying baby.",
    "Try to juggle 3 random objects from the room.",
    "Do your best runway walk across the room.",
    "Send a voice message saying 'I’m Batman' to a random contact.",
    "Say 'I love you' to the first person who messages you next.",
    "Act like a monkey until your next turn.",
    "Spin around 10 times and try to walk straight.",
    "Do your best evil villain laugh.",
    "Eat something without using your hands.",
    "Let the person next to you send one message from your phone.",
    "Act like a news reporter and give a dramatic weather update.",
    "Try to make everyone in the room laugh in 30 seconds.",
    "Pretend to propose to someone in the group.",
    "Do your best runway walk and strike a pose.",
    "Speak only in song lyrics for the next round.",
    "Let someone draw something on your face with a pen (washable).",
    "Make up a 10-second rap about the person on your left.",
    "Do 5 squats while singing your favorite song.",
    "Try to touch your nose with your tongue.",
    "Do your best impression of your favorite cartoon character.",
    "Let another player style your hair however they want.",
    "Do your best slow-motion run like in a movie scene.",
    "Eat a raw onion slice or a spoon of pickle.",
    "Pretend you’re on a cooking show and describe how to make air.",
    "Act like a drama queen for one minute.",
    "Talk with your tongue stuck out until your next turn.",
    "Let someone write a random word on your forehead.",
    "Do a plank for 30 seconds.",
    "Draw something blindfolded and let others guess what it is.",
    "Say 5 random facts about yourself — one must be a lie.",
    "Call someone and just meow until they hang up.",
    "Pretend to cry until someone comforts you.",
    "Do your best superhero pose and say your catchphrase.",
    "Act like a motivational speaker and inspire everyone to study.",
    "Speak without moving your lips for 30 seconds.",
    "Try to make everyone believe you’re an alien visiting Earth.",
    "Let someone else create a new nickname for you — use it for the rest of the game.",
    "Pretend to be a waiter taking a ridiculous order from everyone.",
    "Tell a 20-second story that makes absolutely no sense.",
    "Act like an influencer promoting a random object nearby.",
    "Let someone roast you for 20 seconds without replying.",
    "Do your best impression of a teacher scolding a student.",
    "Hold an imaginary phone conversation for 30 seconds.",
    "Sing the alphabet like it’s a heartbreak song.",
    "Dance without music for 15 seconds.",
    "Act like you’re stuck in slow motion until your next turn.",
    "Let someone in the group choose your next dare.",
    "Say the weirdest pickup line you can think of.",
    "Speak like a YouTuber doing a product unboxing.",
    "Act like you’re in an action movie fight scene — solo.",
    "Pretend you’re narrating your life like a documentary.",
    "Do your best laugh impression of an evil genius.",
    "Do an impression of any animal the group picks.",
    "Talk like a toddler for 30 seconds.",
    "Say your full name backward (or at least try).",
    "Recite a random poem dramatically as if it’s life or death.",
    "Let someone else make up a dare for you — and do it.",
    "Pretend to be a grandparent giving advice to the group.",
    "Give your best impression of a news reporter describing today’s weather.",
    "Do a fake commercial for an imaginary product for 30 seconds.",
    "Act like you’re in a horror movie and you just saw a ghost.",
    "Show the most recent emoji you used and explain it.",
    "Do your best impression of a TikTok dance trend (real or made-up)."
]


def get_random_truth_or_dare():
    return "Dare: " + random.choice(dares) + "\nOR\n" + "Truth: " + random.choice(truths) + "\n"


if __name__ == "__main__":
    print("Welcome to Truth or Dare!")
    print("Play with your friends and have fun.")
    user_input = int(input("How many Games do you want to play? "))
    print("Pick any one from the Following Truth and Dare Question")
    time.sleep(3)
    for _ in range(user_input):
        print(get_random_truth_or_dare())
    time.sleep(3)
    print("\nGood Luck!")
    print("Thanks for playing! Goodbye!")
    exit()